// Generated by jextract

package io.github.ghosthack.libvipsffm.libvips;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Vips extends Vips$shared {

    Vips() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = io.github.ghosthack.libvipsffm.LibVipsLibs.lookup();


    private static class g_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("g_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void (g_free)(gpointer mem)
     * }
     */
    public static FunctionDescriptor g_free$descriptor() {
        return g_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void (g_free)(gpointer mem)
     * }
     */
    public static MethodHandle g_free$handle() {
        return g_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void (g_free)(gpointer mem)
     * }
     */
    public static MemorySegment g_free$address() {
        return g_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void (g_free)(gpointer mem)
     * }
     */
    public static void g_free(MemorySegment mem) {
        var mh$ = g_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("g_free", mem);
            }
            mh$.invokeExact(mem);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class g_object_unref {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("g_object_unref");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void g_object_unref(gpointer object)
     * }
     */
    public static FunctionDescriptor g_object_unref$descriptor() {
        return g_object_unref.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void g_object_unref(gpointer object)
     * }
     */
    public static MethodHandle g_object_unref$handle() {
        return g_object_unref.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void g_object_unref(gpointer object)
     * }
     */
    public static MemorySegment g_object_unref$address() {
        return g_object_unref.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void g_object_unref(gpointer object)
     * }
     */
    public static void g_object_unref(MemorySegment object) {
        var mh$ = g_object_unref.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("g_object_unref", object);
            }
            mh$.invokeExact(object);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int VIPS_INTERPRETATION_sRGB = (int)22L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_INTERPRETATION_sRGB = 22
     * }
     */
    public static int VIPS_INTERPRETATION_sRGB() {
        return VIPS_INTERPRETATION_sRGB;
    }
    private static final int VIPS_FORMAT_UCHAR = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_FORMAT_UCHAR = 0
     * }
     */
    public static int VIPS_FORMAT_UCHAR() {
        return VIPS_FORMAT_UCHAR;
    }
    private static final int VIPS_FORMAT_CHAR = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_FORMAT_CHAR = 1
     * }
     */
    public static int VIPS_FORMAT_CHAR() {
        return VIPS_FORMAT_CHAR;
    }
    private static final int VIPS_FORMAT_USHORT = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_FORMAT_USHORT = 2
     * }
     */
    public static int VIPS_FORMAT_USHORT() {
        return VIPS_FORMAT_USHORT;
    }
    private static final int VIPS_FORMAT_SHORT = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_FORMAT_SHORT = 3
     * }
     */
    public static int VIPS_FORMAT_SHORT() {
        return VIPS_FORMAT_SHORT;
    }
    private static final int VIPS_FORMAT_UINT = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_FORMAT_UINT = 4
     * }
     */
    public static int VIPS_FORMAT_UINT() {
        return VIPS_FORMAT_UINT;
    }
    private static final int VIPS_FORMAT_INT = (int)5L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_FORMAT_INT = 5
     * }
     */
    public static int VIPS_FORMAT_INT() {
        return VIPS_FORMAT_INT;
    }
    private static final int VIPS_FORMAT_FLOAT = (int)6L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_FORMAT_FLOAT = 6
     * }
     */
    public static int VIPS_FORMAT_FLOAT() {
        return VIPS_FORMAT_FLOAT;
    }
    private static final int VIPS_FORMAT_DOUBLE = (int)8L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_FORMAT_DOUBLE = 8
     * }
     */
    public static int VIPS_FORMAT_DOUBLE() {
        return VIPS_FORMAT_DOUBLE;
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern VipsImage *vips_image_new_from_file(const char *name, ...)
     * }
     */
    public static class vips_image_new_from_file {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_POINTER,
                Vips.C_POINTER
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_new_from_file");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_image_new_from_file(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern VipsImage *vips_image_new_from_file(const char *name, ...)
         * }
         */
        public static vips_image_new_from_file makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_image_new_from_file(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public MemorySegment apply(MemorySegment name, Object... x1) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_image_new_from_file", name, x1);
                }
                return (MemorySegment) spreader.invokeExact(name, x1);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static class vips_image_new_from_memory_copy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_POINTER,
            Vips.C_POINTER,
            Vips.C_LONG,
            Vips.C_INT,
            Vips.C_INT,
            Vips.C_INT,
            Vips.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_new_from_memory_copy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern VipsImage *vips_image_new_from_memory_copy(const void *data, size_t size, int width, int height, int bands, VipsBandFormat format)
     * }
     */
    public static FunctionDescriptor vips_image_new_from_memory_copy$descriptor() {
        return vips_image_new_from_memory_copy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern VipsImage *vips_image_new_from_memory_copy(const void *data, size_t size, int width, int height, int bands, VipsBandFormat format)
     * }
     */
    public static MethodHandle vips_image_new_from_memory_copy$handle() {
        return vips_image_new_from_memory_copy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern VipsImage *vips_image_new_from_memory_copy(const void *data, size_t size, int width, int height, int bands, VipsBandFormat format)
     * }
     */
    public static MemorySegment vips_image_new_from_memory_copy$address() {
        return vips_image_new_from_memory_copy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern VipsImage *vips_image_new_from_memory_copy(const void *data, size_t size, int width, int height, int bands, VipsBandFormat format)
     * }
     */
    public static MemorySegment vips_image_new_from_memory_copy(MemorySegment data, long size, int width, int height, int bands, int format) {
        var mh$ = vips_image_new_from_memory_copy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_image_new_from_memory_copy", data, size, width, height, bands, format);
            }
            return (MemorySegment)mh$.invokeExact(data, size, width, height, bands, format);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern VipsImage *vips_image_new_from_buffer(const void *buf, size_t len, const char *option_string, ...)
     * }
     */
    public static class vips_image_new_from_buffer {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_LONG,
                Vips.C_POINTER
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_new_from_buffer");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_image_new_from_buffer(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern VipsImage *vips_image_new_from_buffer(const void *buf, size_t len, const char *option_string, ...)
         * }
         */
        public static vips_image_new_from_buffer makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_image_new_from_buffer(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public MemorySegment apply(MemorySegment buf, long len, MemorySegment option_string, Object... x3) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_image_new_from_buffer", buf, len, option_string, x3);
                }
                return (MemorySegment) spreader.invokeExact(buf, len, option_string, x3);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_image_write_to_file(VipsImage *image, const char *name, ...)
     * }
     */
    public static class vips_image_write_to_file {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_write_to_file");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_image_write_to_file(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_image_write_to_file(VipsImage *image, const char *name, ...)
         * }
         */
        public static vips_image_write_to_file makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_image_write_to_file(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment image, MemorySegment name, Object... x2) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_image_write_to_file", image, name, x2);
                }
                return (int) spreader.invokeExact(image, name, x2);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_image_write_to_buffer(VipsImage *in, const char *suffix, void **buf, size_t *size, ...)
     * }
     */
    public static class vips_image_write_to_buffer {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_POINTER
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_write_to_buffer");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_image_write_to_buffer(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_image_write_to_buffer(VipsImage *in, const char *suffix, void **buf, size_t *size, ...)
         * }
         */
        public static vips_image_write_to_buffer makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_image_write_to_buffer(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment suffix, MemorySegment buf, MemorySegment size, Object... x4) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_image_write_to_buffer", in, suffix, buf, size, x4);
                }
                return (int) spreader.invokeExact(in, suffix, buf, size, x4);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static class vips_image_write_to_memory {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_POINTER,
            Vips.C_POINTER,
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_write_to_memory");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void *vips_image_write_to_memory(VipsImage *in, size_t *size)
     * }
     */
    public static FunctionDescriptor vips_image_write_to_memory$descriptor() {
        return vips_image_write_to_memory.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void *vips_image_write_to_memory(VipsImage *in, size_t *size)
     * }
     */
    public static MethodHandle vips_image_write_to_memory$handle() {
        return vips_image_write_to_memory.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void *vips_image_write_to_memory(VipsImage *in, size_t *size)
     * }
     */
    public static MemorySegment vips_image_write_to_memory$address() {
        return vips_image_write_to_memory.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void *vips_image_write_to_memory(VipsImage *in, size_t *size)
     * }
     */
    public static MemorySegment vips_image_write_to_memory(MemorySegment in, MemorySegment size) {
        var mh$ = vips_image_write_to_memory.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_image_write_to_memory", in, size);
            }
            return (MemorySegment)mh$.invokeExact(in, size);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_error_buffer {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_error_buffer");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern const char *vips_error_buffer()
     * }
     */
    public static FunctionDescriptor vips_error_buffer$descriptor() {
        return vips_error_buffer.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern const char *vips_error_buffer()
     * }
     */
    public static MethodHandle vips_error_buffer$handle() {
        return vips_error_buffer.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern const char *vips_error_buffer()
     * }
     */
    public static MemorySegment vips_error_buffer$address() {
        return vips_error_buffer.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern const char *vips_error_buffer()
     * }
     */
    public static MemorySegment vips_error_buffer() {
        var mh$ = vips_error_buffer.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_error_buffer");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_error_clear {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_error_clear");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void vips_error_clear()
     * }
     */
    public static FunctionDescriptor vips_error_clear$descriptor() {
        return vips_error_clear.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void vips_error_clear()
     * }
     */
    public static MethodHandle vips_error_clear$handle() {
        return vips_error_clear.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void vips_error_clear()
     * }
     */
    public static MemorySegment vips_error_clear$address() {
        return vips_error_clear.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void vips_error_clear()
     * }
     */
    public static void vips_error_clear() {
        var mh$ = vips_error_clear.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_error_clear");
            }
            mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_image_get_width {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_INT,
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_get_width");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int vips_image_get_width(const VipsImage *image)
     * }
     */
    public static FunctionDescriptor vips_image_get_width$descriptor() {
        return vips_image_get_width.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int vips_image_get_width(const VipsImage *image)
     * }
     */
    public static MethodHandle vips_image_get_width$handle() {
        return vips_image_get_width.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int vips_image_get_width(const VipsImage *image)
     * }
     */
    public static MemorySegment vips_image_get_width$address() {
        return vips_image_get_width.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int vips_image_get_width(const VipsImage *image)
     * }
     */
    public static int vips_image_get_width(MemorySegment image) {
        var mh$ = vips_image_get_width.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_image_get_width", image);
            }
            return (int)mh$.invokeExact(image);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_image_get_height {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_INT,
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_get_height");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int vips_image_get_height(const VipsImage *image)
     * }
     */
    public static FunctionDescriptor vips_image_get_height$descriptor() {
        return vips_image_get_height.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int vips_image_get_height(const VipsImage *image)
     * }
     */
    public static MethodHandle vips_image_get_height$handle() {
        return vips_image_get_height.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int vips_image_get_height(const VipsImage *image)
     * }
     */
    public static MemorySegment vips_image_get_height$address() {
        return vips_image_get_height.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int vips_image_get_height(const VipsImage *image)
     * }
     */
    public static int vips_image_get_height(MemorySegment image) {
        var mh$ = vips_image_get_height.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_image_get_height", image);
            }
            return (int)mh$.invokeExact(image);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_image_get_bands {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_INT,
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_get_bands");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int vips_image_get_bands(const VipsImage *image)
     * }
     */
    public static FunctionDescriptor vips_image_get_bands$descriptor() {
        return vips_image_get_bands.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int vips_image_get_bands(const VipsImage *image)
     * }
     */
    public static MethodHandle vips_image_get_bands$handle() {
        return vips_image_get_bands.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int vips_image_get_bands(const VipsImage *image)
     * }
     */
    public static MemorySegment vips_image_get_bands$address() {
        return vips_image_get_bands.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int vips_image_get_bands(const VipsImage *image)
     * }
     */
    public static int vips_image_get_bands(MemorySegment image) {
        var mh$ = vips_image_get_bands.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_image_get_bands", image);
            }
            return (int)mh$.invokeExact(image);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_image_get_format {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_INT,
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_get_format");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern VipsBandFormat vips_image_get_format(const VipsImage *image)
     * }
     */
    public static FunctionDescriptor vips_image_get_format$descriptor() {
        return vips_image_get_format.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern VipsBandFormat vips_image_get_format(const VipsImage *image)
     * }
     */
    public static MethodHandle vips_image_get_format$handle() {
        return vips_image_get_format.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern VipsBandFormat vips_image_get_format(const VipsImage *image)
     * }
     */
    public static MemorySegment vips_image_get_format$address() {
        return vips_image_get_format.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern VipsBandFormat vips_image_get_format(const VipsImage *image)
     * }
     */
    public static int vips_image_get_format(MemorySegment image) {
        var mh$ = vips_image_get_format.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_image_get_format", image);
            }
            return (int)mh$.invokeExact(image);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_image_get_interpretation {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_INT,
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_image_get_interpretation");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern VipsInterpretation vips_image_get_interpretation(const VipsImage *image)
     * }
     */
    public static FunctionDescriptor vips_image_get_interpretation$descriptor() {
        return vips_image_get_interpretation.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern VipsInterpretation vips_image_get_interpretation(const VipsImage *image)
     * }
     */
    public static MethodHandle vips_image_get_interpretation$handle() {
        return vips_image_get_interpretation.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern VipsInterpretation vips_image_get_interpretation(const VipsImage *image)
     * }
     */
    public static MemorySegment vips_image_get_interpretation$address() {
        return vips_image_get_interpretation.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern VipsInterpretation vips_image_get_interpretation(const VipsImage *image)
     * }
     */
    public static int vips_image_get_interpretation(MemorySegment image) {
        var mh$ = vips_image_get_interpretation.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_image_get_interpretation", image);
            }
            return (int)mh$.invokeExact(image);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_cache_set_max {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Vips.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_cache_set_max");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max(int max)
     * }
     */
    public static FunctionDescriptor vips_cache_set_max$descriptor() {
        return vips_cache_set_max.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max(int max)
     * }
     */
    public static MethodHandle vips_cache_set_max$handle() {
        return vips_cache_set_max.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max(int max)
     * }
     */
    public static MemorySegment vips_cache_set_max$address() {
        return vips_cache_set_max.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void vips_cache_set_max(int max)
     * }
     */
    public static void vips_cache_set_max(int max) {
        var mh$ = vips_cache_set_max.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_cache_set_max", max);
            }
            mh$.invokeExact(max);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_cache_set_max_mem {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Vips.C_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_cache_set_max_mem");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max_mem(size_t max_mem)
     * }
     */
    public static FunctionDescriptor vips_cache_set_max_mem$descriptor() {
        return vips_cache_set_max_mem.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max_mem(size_t max_mem)
     * }
     */
    public static MethodHandle vips_cache_set_max_mem$handle() {
        return vips_cache_set_max_mem.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max_mem(size_t max_mem)
     * }
     */
    public static MemorySegment vips_cache_set_max_mem$address() {
        return vips_cache_set_max_mem.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void vips_cache_set_max_mem(size_t max_mem)
     * }
     */
    public static void vips_cache_set_max_mem(long max_mem) {
        var mh$ = vips_cache_set_max_mem.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_cache_set_max_mem", max_mem);
            }
            mh$.invokeExact(max_mem);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_cache_set_max_files {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Vips.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_cache_set_max_files");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max_files(int max_files)
     * }
     */
    public static FunctionDescriptor vips_cache_set_max_files$descriptor() {
        return vips_cache_set_max_files.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max_files(int max_files)
     * }
     */
    public static MethodHandle vips_cache_set_max_files$handle() {
        return vips_cache_set_max_files.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void vips_cache_set_max_files(int max_files)
     * }
     */
    public static MemorySegment vips_cache_set_max_files$address() {
        return vips_cache_set_max_files.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void vips_cache_set_max_files(int max_files)
     * }
     */
    public static void vips_cache_set_max_files(int max_files) {
        var mh$ = vips_cache_set_max_files.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_cache_set_max_files", max_files);
            }
            mh$.invokeExact(max_files);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_linear1(VipsImage *in, VipsImage **out, double a, double b, ...)
     * }
     */
    public static class vips_linear1 {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_DOUBLE,
                Vips.C_DOUBLE
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_linear1");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_linear1(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_linear1(VipsImage *in, VipsImage **out, double a, double b, ...)
         * }
         */
        public static vips_linear1 makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_linear1(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, double a, double b, Object... x4) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_linear1", in, out, a, b, x4);
                }
                return (int) spreader.invokeExact(in, out, a, b, x4);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_invert(VipsImage *in, VipsImage **out, ...)
     * }
     */
    public static class vips_invert {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_invert");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_invert(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_invert(VipsImage *in, VipsImage **out, ...)
         * }
         */
        public static vips_invert makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_invert(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, Object... x2) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_invert", in, out, x2);
                }
                return (int) spreader.invokeExact(in, out, x2);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_avg(VipsImage *in, double *out, ...)
     * }
     */
    public static class vips_avg {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_avg");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_avg(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_avg(VipsImage *in, double *out, ...)
         * }
         */
        public static vips_avg makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_avg(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, Object... x2) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_avg", in, out, x2);
                }
                return (int) spreader.invokeExact(in, out, x2);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }
    private static final int VIPS_DIRECTION_HORIZONTAL = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_DIRECTION_HORIZONTAL = 0
     * }
     */
    public static int VIPS_DIRECTION_HORIZONTAL() {
        return VIPS_DIRECTION_HORIZONTAL;
    }
    private static final int VIPS_DIRECTION_VERTICAL = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_DIRECTION_VERTICAL = 1
     * }
     */
    public static int VIPS_DIRECTION_VERTICAL() {
        return VIPS_DIRECTION_VERTICAL;
    }
    private static final int VIPS_ANGLE_D0 = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_ANGLE_D0 = 0
     * }
     */
    public static int VIPS_ANGLE_D0() {
        return VIPS_ANGLE_D0;
    }
    private static final int VIPS_ANGLE_D90 = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_ANGLE_D90 = 1
     * }
     */
    public static int VIPS_ANGLE_D90() {
        return VIPS_ANGLE_D90;
    }
    private static final int VIPS_ANGLE_D180 = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_ANGLE_D180 = 2
     * }
     */
    public static int VIPS_ANGLE_D180() {
        return VIPS_ANGLE_D180;
    }
    private static final int VIPS_ANGLE_D270 = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.VIPS_ANGLE_D270 = 3
     * }
     */
    public static int VIPS_ANGLE_D270() {
        return VIPS_ANGLE_D270;
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_flip(VipsImage *in, VipsImage **out, VipsDirection direction, ...)
     * }
     */
    public static class vips_flip {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_flip");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_flip(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_flip(VipsImage *in, VipsImage **out, VipsDirection direction, ...)
         * }
         */
        public static vips_flip makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_flip(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, int direction, Object... x3) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_flip", in, out, direction, x3);
                }
                return (int) spreader.invokeExact(in, out, direction, x3);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_extract_area(VipsImage *in, VipsImage **out, int left, int top, int width, int height, ...)
     * }
     */
    public static class vips_extract_area {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_INT,
                Vips.C_INT,
                Vips.C_INT,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_extract_area");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_extract_area(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_extract_area(VipsImage *in, VipsImage **out, int left, int top, int width, int height, ...)
         * }
         */
        public static vips_extract_area makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_extract_area(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, int left, int top, int width, int height, Object... x6) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_extract_area", in, out, left, top, width, height, x6);
                }
                return (int) spreader.invokeExact(in, out, left, top, width, height, x6);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_crop(VipsImage *in, VipsImage **out, int left, int top, int width, int height, ...)
     * }
     */
    public static class vips_crop {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_INT,
                Vips.C_INT,
                Vips.C_INT,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_crop");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_crop(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_crop(VipsImage *in, VipsImage **out, int left, int top, int width, int height, ...)
         * }
         */
        public static vips_crop makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_crop(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, int left, int top, int width, int height, Object... x6) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_crop", in, out, left, top, width, height, x6);
                }
                return (int) spreader.invokeExact(in, out, left, top, width, height, x6);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_rot(VipsImage *in, VipsImage **out, VipsAngle angle, ...)
     * }
     */
    public static class vips_rot {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_rot");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_rot(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_rot(VipsImage *in, VipsImage **out, VipsAngle angle, ...)
         * }
         */
        public static vips_rot makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_rot(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, int angle, Object... x3) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_rot", in, out, angle, x3);
                }
                return (int) spreader.invokeExact(in, out, angle, x3);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_autorot(VipsImage *in, VipsImage **out, ...)
     * }
     */
    public static class vips_autorot {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_autorot");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_autorot(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_autorot(VipsImage *in, VipsImage **out, ...)
         * }
         */
        public static vips_autorot makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_autorot(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, Object... x2) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_autorot", in, out, x2);
                }
                return (int) spreader.invokeExact(in, out, x2);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_cast(VipsImage *in, VipsImage **out, VipsBandFormat format, ...)
     * }
     */
    public static class vips_cast {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_cast");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_cast(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_cast(VipsImage *in, VipsImage **out, VipsBandFormat format, ...)
         * }
         */
        public static vips_cast makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_cast(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, int format, Object... x3) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_cast", in, out, format, x3);
                }
                return (int) spreader.invokeExact(in, out, format, x3);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_thumbnail(const char *filename, VipsImage **out, int width, ...)
     * }
     */
    public static class vips_thumbnail {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_thumbnail");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_thumbnail(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_thumbnail(const char *filename, VipsImage **out, int width, ...)
         * }
         */
        public static vips_thumbnail makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_thumbnail(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment filename, MemorySegment out, int width, Object... x3) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_thumbnail", filename, out, width, x3);
                }
                return (int) spreader.invokeExact(filename, out, width, x3);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_thumbnail_buffer(void *buf, size_t len, VipsImage **out, int width, ...)
     * }
     */
    public static class vips_thumbnail_buffer {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_LONG,
                Vips.C_POINTER,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_thumbnail_buffer");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_thumbnail_buffer(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_thumbnail_buffer(void *buf, size_t len, VipsImage **out, int width, ...)
         * }
         */
        public static vips_thumbnail_buffer makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_thumbnail_buffer(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment buf, long len, MemorySegment out, int width, Object... x4) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_thumbnail_buffer", buf, len, out, width, x4);
                }
                return (int) spreader.invokeExact(buf, len, out, width, x4);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_thumbnail_image(VipsImage *in, VipsImage **out, int width, ...)
     * }
     */
    public static class vips_thumbnail_image {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_thumbnail_image");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_thumbnail_image(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_thumbnail_image(VipsImage *in, VipsImage **out, int width, ...)
         * }
         */
        public static vips_thumbnail_image makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_thumbnail_image(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, int width, Object... x3) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_thumbnail_image", in, out, width, x3);
                }
                return (int) spreader.invokeExact(in, out, width, x3);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_resize(VipsImage *in, VipsImage **out, double scale, ...)
     * }
     */
    public static class vips_resize {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_DOUBLE
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_resize");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_resize(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_resize(VipsImage *in, VipsImage **out, double scale, ...)
         * }
         */
        public static vips_resize makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_resize(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, double scale, Object... x3) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_resize", in, out, scale, x3);
                }
                return (int) spreader.invokeExact(in, out, scale, x3);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * extern int vips_colourspace(VipsImage *in, VipsImage **out, VipsInterpretation space, ...)
     * }
     */
    public static class vips_colourspace {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Vips.C_INT,
                Vips.C_POINTER,
                Vips.C_POINTER,
                Vips.C_INT
            );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_colourspace");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private vips_colourspace(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * extern int vips_colourspace(VipsImage *in, VipsImage **out, VipsInterpretation space, ...)
         * }
         */
        public static vips_colourspace makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new vips_colourspace(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(MemorySegment in, MemorySegment out, int space, Object... x3) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("vips_colourspace", in, out, space, x3);
                }
                return (int) spreader.invokeExact(in, out, space, x3);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static class vips_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_INT,
            Vips.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int vips_init(const char *argv0)
     * }
     */
    public static FunctionDescriptor vips_init$descriptor() {
        return vips_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int vips_init(const char *argv0)
     * }
     */
    public static MethodHandle vips_init$handle() {
        return vips_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int vips_init(const char *argv0)
     * }
     */
    public static MemorySegment vips_init$address() {
        return vips_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int vips_init(const char *argv0)
     * }
     */
    public static int vips_init(MemorySegment argv0) {
        var mh$ = vips_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_init", argv0);
            }
            return (int)mh$.invokeExact(argv0);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_shutdown {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_shutdown");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void vips_shutdown()
     * }
     */
    public static FunctionDescriptor vips_shutdown$descriptor() {
        return vips_shutdown.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void vips_shutdown()
     * }
     */
    public static MethodHandle vips_shutdown$handle() {
        return vips_shutdown.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void vips_shutdown()
     * }
     */
    public static MemorySegment vips_shutdown$address() {
        return vips_shutdown.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void vips_shutdown()
     * }
     */
    public static void vips_shutdown() {
        var mh$ = vips_shutdown.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_shutdown");
            }
            mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_version_string {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_version_string");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern const char *vips_version_string()
     * }
     */
    public static FunctionDescriptor vips_version_string$descriptor() {
        return vips_version_string.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern const char *vips_version_string()
     * }
     */
    public static MethodHandle vips_version_string$handle() {
        return vips_version_string.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern const char *vips_version_string()
     * }
     */
    public static MemorySegment vips_version_string$address() {
        return vips_version_string.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern const char *vips_version_string()
     * }
     */
    public static MemorySegment vips_version_string() {
        var mh$ = vips_version_string.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_version_string");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class vips_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Vips.C_INT,
            Vips.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("vips_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int vips_version(int flag)
     * }
     */
    public static FunctionDescriptor vips_version$descriptor() {
        return vips_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int vips_version(int flag)
     * }
     */
    public static MethodHandle vips_version$handle() {
        return vips_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int vips_version(int flag)
     * }
     */
    public static MemorySegment vips_version$address() {
        return vips_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int vips_version(int flag)
     * }
     */
    public static int vips_version(int flag) {
        var mh$ = vips_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("vips_version", flag);
            }
            return (int)mh$.invokeExact(flag);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

